services:
  live:
    build:
      context: ./
      dockerfile: docker/jdk/Dockerfile
      #target: build - enable this to use JDK image
    environment:
      - RABBITMQ_HOST=rabbitmq
    env_file: .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 127.0.0.1:8080:8080

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:v2.26.1
    #ports:
    #  - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./docker/prometheus:/etc/prometheus
    environment:
      - ACTUATOR_USER=admin
      - ACTUATOR_PASSWORD=admin
    command: --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - live

  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus-data:
  grafana-data: