# The JWT public key's location relative to src/main/resources.
antragsgruen:
  jwt.key.public: public.key
  ws.origins: http://*.antragsgruen.test

# RabbitMQ configuration
rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE:antragsgruen-exchange}
    name_dead: ${RABBITMQ_EXCHANGE_DEAD:antragsgruen-exchange-dead}
  queue:
    user: ${RABBITMQ_QUEUE_USER:antragsgruen-queue-user}
    user_dead: ${RABBITMQ_QUEUE_SPEECH:antragsgruen-queue-user-dead}
    speech: ${RABBITMQ_QUEUE_SPEECH:antragsgruen-queue-speech}
    speech_dead: ${RABBITMQ_QUEUE_SPEECH:antragsgruen-queue-speech-dead}
  routing:
    user: user.*.*.*
    speech: speech.*.*

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  #endpoint:
  #  env:
  #    show-values: always

#logging:
#  level:
#    root: DEBUG
#    de.antragsgruen.live: DEBUG

spring.security.user:
  name: ${ACTUATOR_USER:admin}
  password: ${ACTUATOR_PWD:admin}
  roles:
    - ADMIN