global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'antragsgruen_live'
    metrics_path: /actuator/prometheus
    # https://github.com/prometheus/prometheus/issues/10554 - no support for environment variables
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets:
          - 'live:8080'