name: Test project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.13
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install assets
        run: npm ci

      - name: Run checkstyle
        run: mvn checkstyle:check

      - name: Run spotbugs
        run: mvn spotbugs:check

      - name: Run integration tests
        run: mvn test
